// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TAAS.NetMAUI.Infrastructure.Data;

#nullable disable

namespace TAAS.NetMAUI.Infrastructure.Migrations
{
    [DbContext(typeof(TaasDbContext))]
    [Migration("20251218203709_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.AuditAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AuditPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CoordinatorAuditorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MainTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StrategyPlanPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaskTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuditPeriodId");

                    b.HasIndex("CoordinatorAuditorId");

                    b.HasIndex("MainTaskId");

                    b.HasIndex("StrategyPlanPeriodId");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskTypeId");

                    b.ToTable("AuditAssignments");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.AuditAssignmentAuditor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuditAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuditorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuditAssignmentId");

                    b.HasIndex("AuditorId");

                    b.ToTable("AuditAssignmentAuditors");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.AuditAssignmentFinancialAuditType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuditAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuditTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuditAssignmentId");

                    b.HasIndex("AuditTypeId");

                    b.ToTable("AuditAssignmentFinancialAuditTypes");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.AuditAssignmentOperationAuditType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuditAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuditTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuditAssignmentId");

                    b.HasIndex("AuditTypeId");

                    b.ToTable("AuditAssignmentOperationAuditTypes");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.AuditAssignmentTemporaryAuditor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuditAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuditorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuditAssignmentId");

                    b.HasIndex("AuditorId");

                    b.ToTable("AuditAssignmentTemporaryAuditors");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.AuditPeriod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditPeriods");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.AuditProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("InstitutionId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("KeyRequirementId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SpecificFunctionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("KeyRequirementId");

                    b.HasIndex("SpecificFunctionId");

                    b.ToTable("AuditPrograms");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.AuditType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("AuditTypes");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.Auditor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("MachineName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Auditors");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.Checklist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuditAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AuditProgramId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuditTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChecklistTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReviewedAuditorId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SamplingRowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Turkish")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuditAssignmentId");

                    b.HasIndex("AuditProgramId");

                    b.HasIndex("AuditTypeId");

                    b.HasIndex("ChecklistTemplateId");

                    b.HasIndex("ReviewedAuditorId");

                    b.ToTable("Checklists");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.ChecklistAuditor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuditorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChecklistId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuditorId");

                    b.HasIndex("ChecklistId");

                    b.ToTable("ChecklistAuditors");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.ChecklistDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .HasColumnType("TEXT");

                    b.Property<long>("ChecklistId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChecklistTemplateDetailId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExplanationFormatted")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("ChecklistTemplateDetailId");

                    b.ToTable("ChecklistDetails");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.ChecklistDetailTaasFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChecklistDetailId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Synched")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaasFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistDetailId");

                    b.HasIndex("TaasFileId");

                    b.ToTable("ChecklistDetailTaasFiles");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.ChecklistHeader", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChecklistId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChecklistTemplateHeaderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("ChecklistTemplateHeaderId");

                    b.ToTable("ChecklistHeaders");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.ChecklistTaasFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChecklistId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Synched")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaasFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("TaasFileId");

                    b.ToTable("ChecklistTaasFiles");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.ChecklistTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChecklistTemplates");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.ChecklistTemplateDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChecklistTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommentTr")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Title")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistTemplateId");

                    b.ToTable("ChecklistTemplateDetails");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.ChecklistTemplateHeader", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChecklistTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistTemplateId");

                    b.ToTable("ChecklistTemplateHeaders");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.Institution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegisteredName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.KeyRequirement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("GeneralCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("KeyRequirements");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.MainTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("MainTasks");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.SpecificFunction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("GeneralCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("SpecificFunctions");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.StrategyPlanPeriod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StrategyPlanPeriods");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.TaasFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ApiId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Synched")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TaasFile");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.Task", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.TaskType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<long>("SystemAuditTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SystemAuditTypeId");

                    b.ToTable("TaskTypes");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.AuditAssignment", b =>
                {
                    b.HasOne("TAAS.NetMAUI.Core.Entities.AuditPeriod", "AuditPeriod")
                        .WithMany()
                        .HasForeignKey("AuditPeriodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TAAS.NetMAUI.Core.Entities.Auditor", "CoordinatorAuditor")
                        .WithMany()
                        .HasForeignKey("CoordinatorAuditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TAAS.NetMAUI.Core.Entities.MainTask", "MainTask")
                        .WithMany()
                        .HasForeignKey("MainTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TAAS.NetMAUI.Core.Entities.StrategyPlanPeriod", "StrategyPlanPeriod")
                        .WithMany()
                        .HasForeignKey("StrategyPlanPeriodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TAAS.NetMAUI.Core.Entities.Task", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TAAS.NetMAUI.Core.Entities.TaskType", "TaskType")
                        .WithMany()
                        .HasForeignKey("TaskTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditPeriod");

                    b.Navigation("CoordinatorAuditor");

                    b.Navigation("MainTask");

                    b.Navigation("StrategyPlanPeriod");

                    b.Navigation("Task");

                    b.Navigation("TaskType");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.AuditAssignmentAuditor", b =>
                {
                    b.HasOne("TAAS.NetMAUI.Core.Entities.AuditAssignment", "AuditAssignment")
                        .WithMany("AuditAssignmentAuditors")
                        .HasForeignKey("AuditAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TAAS.NetMAUI.Core.Entities.Auditor", "Auditor")
                        .WithMany("AuditAssignmentAuditors")
                        .HasForeignKey("AuditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditAssignment");

                    b.Navigation("Auditor");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.AuditAssignmentFinancialAuditType", b =>
                {
                    b.HasOne("TAAS.NetMAUI.Core.Entities.AuditAssignment", "AuditAssignment")
                        .WithMany("AuditAssignmentFinancialAuditTypes")
                        .HasForeignKey("AuditAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TAAS.NetMAUI.Core.Entities.AuditType", "AuditType")
                        .WithMany("AuditAssignmentFinancialAuditTypes")
                        .HasForeignKey("AuditTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditAssignment");

                    b.Navigation("AuditType");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.AuditAssignmentOperationAuditType", b =>
                {
                    b.HasOne("TAAS.NetMAUI.Core.Entities.AuditAssignment", "AuditAssignment")
                        .WithMany("AuditAssignmentOperationAuditTypes")
                        .HasForeignKey("AuditAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TAAS.NetMAUI.Core.Entities.AuditType", "AuditType")
                        .WithMany("AuditAssignmentOperationAuditTypes")
                        .HasForeignKey("AuditTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditAssignment");

                    b.Navigation("AuditType");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.AuditAssignmentTemporaryAuditor", b =>
                {
                    b.HasOne("TAAS.NetMAUI.Core.Entities.AuditAssignment", "AuditAssignment")
                        .WithMany("AuditAssignmentTemporaryAuditors")
                        .HasForeignKey("AuditAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TAAS.NetMAUI.Core.Entities.Auditor", "Auditor")
                        .WithMany("AuditAssignmentTemporaryAuditors")
                        .HasForeignKey("AuditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditAssignment");

                    b.Navigation("Auditor");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.AuditProgram", b =>
                {
                    b.HasOne("TAAS.NetMAUI.Core.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TAAS.NetMAUI.Core.Entities.KeyRequirement", "KeyRequirement")
                        .WithMany()
                        .HasForeignKey("KeyRequirementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TAAS.NetMAUI.Core.Entities.SpecificFunction", "SpecificFunction")
                        .WithMany()
                        .HasForeignKey("SpecificFunctionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Institution");

                    b.Navigation("KeyRequirement");

                    b.Navigation("SpecificFunction");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.Checklist", b =>
                {
                    b.HasOne("TAAS.NetMAUI.Core.Entities.AuditAssignment", "AuditAssignment")
                        .WithMany()
                        .HasForeignKey("AuditAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TAAS.NetMAUI.Core.Entities.AuditProgram", "AuditProgram")
                        .WithMany()
                        .HasForeignKey("AuditProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TAAS.NetMAUI.Core.Entities.AuditType", "AuditType")
                        .WithMany()
                        .HasForeignKey("AuditTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TAAS.NetMAUI.Core.Entities.ChecklistTemplate", "ChecklistTemplate")
                        .WithMany()
                        .HasForeignKey("ChecklistTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TAAS.NetMAUI.Core.Entities.Auditor", "ReviewedAuditor")
                        .WithMany()
                        .HasForeignKey("ReviewedAuditorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AuditAssignment");

                    b.Navigation("AuditProgram");

                    b.Navigation("AuditType");

                    b.Navigation("ChecklistTemplate");

                    b.Navigation("ReviewedAuditor");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.ChecklistAuditor", b =>
                {
                    b.HasOne("TAAS.NetMAUI.Core.Entities.Auditor", "Auditor")
                        .WithMany("ChecklistAuditors")
                        .HasForeignKey("AuditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TAAS.NetMAUI.Core.Entities.Checklist", "Checklist")
                        .WithMany("ChecklistAuditors")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auditor");

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.ChecklistDetail", b =>
                {
                    b.HasOne("TAAS.NetMAUI.Core.Entities.Checklist", "Checklist")
                        .WithMany("ChecklistDetails")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TAAS.NetMAUI.Core.Entities.ChecklistTemplateDetail", "ChecklistTemplateDetail")
                        .WithMany()
                        .HasForeignKey("ChecklistTemplateDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checklist");

                    b.Navigation("ChecklistTemplateDetail");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.ChecklistDetailTaasFile", b =>
                {
                    b.HasOne("TAAS.NetMAUI.Core.Entities.ChecklistDetail", "ChecklistDetail")
                        .WithMany("ChecklistDetailTaasFiles")
                        .HasForeignKey("ChecklistDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TAAS.NetMAUI.Core.Entities.TaasFile", "TaasFile")
                        .WithMany("ChecklistDetailTaasFiles")
                        .HasForeignKey("TaasFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChecklistDetail");

                    b.Navigation("TaasFile");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.ChecklistHeader", b =>
                {
                    b.HasOne("TAAS.NetMAUI.Core.Entities.Checklist", "Checklist")
                        .WithMany("ChecklistHeaders")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TAAS.NetMAUI.Core.Entities.ChecklistTemplateHeader", "ChecklistTemplateHeader")
                        .WithMany()
                        .HasForeignKey("ChecklistTemplateHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checklist");

                    b.Navigation("ChecklistTemplateHeader");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.ChecklistTaasFile", b =>
                {
                    b.HasOne("TAAS.NetMAUI.Core.Entities.Checklist", "Checklist")
                        .WithMany("ChecklistTaasFiles")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TAAS.NetMAUI.Core.Entities.TaasFile", "TaasFile")
                        .WithMany("ChecklistTaasFiles")
                        .HasForeignKey("TaasFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checklist");

                    b.Navigation("TaasFile");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.ChecklistTemplateDetail", b =>
                {
                    b.HasOne("TAAS.NetMAUI.Core.Entities.ChecklistTemplate", "ChecklistTemplate")
                        .WithMany()
                        .HasForeignKey("ChecklistTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistTemplate");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.ChecklistTemplateHeader", b =>
                {
                    b.HasOne("TAAS.NetMAUI.Core.Entities.ChecklistTemplate", "ChecklistTemplate")
                        .WithMany()
                        .HasForeignKey("ChecklistTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistTemplate");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.TaskType", b =>
                {
                    b.HasOne("TAAS.NetMAUI.Core.Entities.AuditType", "SystemAuditType")
                        .WithMany()
                        .HasForeignKey("SystemAuditTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SystemAuditType");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.AuditAssignment", b =>
                {
                    b.Navigation("AuditAssignmentAuditors");

                    b.Navigation("AuditAssignmentFinancialAuditTypes");

                    b.Navigation("AuditAssignmentOperationAuditTypes");

                    b.Navigation("AuditAssignmentTemporaryAuditors");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.AuditType", b =>
                {
                    b.Navigation("AuditAssignmentFinancialAuditTypes");

                    b.Navigation("AuditAssignmentOperationAuditTypes");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.Auditor", b =>
                {
                    b.Navigation("AuditAssignmentAuditors");

                    b.Navigation("AuditAssignmentTemporaryAuditors");

                    b.Navigation("ChecklistAuditors");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.Checklist", b =>
                {
                    b.Navigation("ChecklistAuditors");

                    b.Navigation("ChecklistDetails");

                    b.Navigation("ChecklistHeaders");

                    b.Navigation("ChecklistTaasFiles");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.ChecklistDetail", b =>
                {
                    b.Navigation("ChecklistDetailTaasFiles");
                });

            modelBuilder.Entity("TAAS.NetMAUI.Core.Entities.TaasFile", b =>
                {
                    b.Navigation("ChecklistDetailTaasFiles");

                    b.Navigation("ChecklistTaasFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
